### ISSUE TITLE
Custom service

### ISSUE THREAD

**Issue by cucko** [mauimauer/cheapcast#6]
An option to add custom service(by specifying receiverPage url and protocol) for development purposes would be awesome.

**Comment by mauimauer** [comment]
Already on my list :D

**Comment by cucko** [comment]
nice!!!
keep up the good work.

**Comment by mauimauer** [comment]
A new version supporting this is underway to the Play Store.

To register a custom App enable the "Custom Service"-flag in the Preference Activity.

You can see registered apps at: http://<yourDevice>:8008

To register a new app issue a raw POST to http://<yourDevice>:8008/registerApp
JSON Payload:

{"appName":"YourApp", "appUrl": "http://www.yourapp.com/app?$query", "protocols": [ "ramp" ]}

**Comment by cucko** [comment]
perfect. thank you

**Comment by cucko** [comment]
i'm trying to build chrome sender app
i registered my app, but its listed on :8008
but cast_api.addReceiverListener("MyApp", onReceiverList);
is returning empty list. 
should i restart the service after registering the app? 
as i can see, on restart service list of registered apps is reverted to default.

**Comment by mauimauer** [comment]
Hmmm, actually I've never looked at the client side of the ChromeCast SDK.

Restarting the Service will reset the App list.
What does GET :8008/apps/<YourAppName> return after registering your app?

**Comment by cucko** [comment]
:8008/apps/ returns server error (when opening in browser)
:8008 gives list of all registered app, including mine

**Comment by mauimauer** [comment]
Whoops. I meant /apps/YourAppName

**Comment by cucko** [comment]
hmm.. how to post xml here :)

ok, via email

**Comment by cucko** [comment]
<service xmlns="urn:dial-multiscreen-org:schemas:dial">
<name>MyCloudPlayer</name>
<options allowStop="true"/>
<activity-status xmlns="urn:chrome.google.com:cast">
<description>Legacy</description>
</activity-status>
<servicedata xmlns="urn:chrome.google.com:cast">
<connectionSvcURL/>
<protocols/>
</servicedata>
<state>stopped</state>
</service>

On Mon, Aug 12, 2013 at 6:44 PM, Sebastian Mauer
notifications@github.comwrote:

> Whoops. I meant /apps/YourAppName
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/mauimauer/cheapcast/issues/6#issuecomment-22507092
> .

## 

Goran Sirkarovski Cucko

**Comment by cucko** [comment]
everything works fine with last update. thanks.
