### ISSUE TITLE
ChomeCast extension support.

### ISSUE THREAD

**Issue by ghost** [mauimauer/cheapcast#9]
Attempting to stream a page from desktop (with https://chrome.google.com/webstore/detail/google-cast/boadgeojelhgndaghljhdicfkmllpafd) to Nexus 7 (2012) results in a black screen on the device, and results in this error on the chrome extension:

"Unable to cast to CheapCast"
An unexpected error occurred. Please try the following:
Try to cast again
Verify your network connectivity'

I was unable to find logging on either side, if someone can point me in the right direction I will also post those.

**Comment by mauimauer** [comment]
Chromecasting Tabs is currently not supported. I don't even have a ChromeCast Device, so until I get one this feature is unlikely to get implemented and/or looked at.

Sorry.
